/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    public static String subsequences(String word) {


    	if (word.isEmpty()){
    		// Warunek poczatkowy
    		return "";
    	} else {
    		char firstLetter = word.charAt(0);
    		String restOfWord = word.substring(1);
    		
    		String subsequencesOfRest = subsequences(restOfWord);
    		
    		String result = "";
    		
    		
    	}
    	
        return word;
    }
}
